### ISSUE TITLE
SessionID

### ISSUE THREAD

**Issue by louisza** [InitialState/python_appender#1]
self.SessionId = str(uuid.uuid4()) in streamer.py

I am certainly no good at Python, so please take that in consideration:

Writing to the same bucket is possible (according to a recent webinar) if you use the same SessionId.
Looking at the code, it seems like specifying a SessionId will be pointless as the code just generates a new one...

**Comment by davidsulpy** [comment]
@louisza I'm excited to let you know that version 0.0.25 was officially released and should fix your issue completely!

Now, all you have to do is specify the same `bucket_key` in the constructor of the Streamer like this:

```python
streamer = Streamer(bucket_name="louisza's bucket", bucket_key="reference_key", access_key="[AccessKey]")
```

I'm going to close this enhancement as finished. But feel free to reach out if you have any more questions!

Thanks,
David
